# Generated by Django 4.0.5 on 2022-06-26 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0006_company_reg_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='status',
            field=models.CharField(choices=[('acc', 'Accepted'), ('pen', 'Pending'), ('app', 'Applied'), ('rej', 'Rejected')], default='app', max_length=3),
        ),
    ]
