# Generated by Django 4.0.5 on 2022-06-26 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0006_remove_candidate_bachelor_degree_candidate_degree'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='contact_address',
            new_name='company_address',
        ),
        migrations.AddField(
            model_name='company',
            name='company_registration_no',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='company_start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
