# Generated by Django 4.0.5 on 2022-06-26 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0007_rename_contact_address_company_company_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='company_start_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date started'),
        ),
    ]
