# Generated by Django 4.0.5 on 2022-06-27 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0007_alter_candidate_status'),
        ('company', '0008_alter_company_company_start_date'),
    ]

    operations = [
    ]
