# Generated by Django 4.0.5 on 2022-06-27 17:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0009_merge_20220627_2115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='cv',
            field=models.FileField(default=django.utils.timezone.now, upload_to='company/candidates/files/'),
            preserve_default=False,
        ),
    ]
