# Generated by Django 4.0.5 on 2022-06-27 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0010_alter_candidate_cv'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='cv',
            field=models.FileField(upload_to='company/candidate/cvs/'),
        ),
    ]
