# Generated by Django 4.0.5 on 2022-06-27 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0011_alter_candidate_cv'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='reg_no',
        ),
        migrations.AlterField(
            model_name='candidate',
            name='cv',
            field=models.FileField(blank=True, null=True, upload_to='company/candidate/cvs/'),
        ),
    ]
