# Generated by Django 4.0.5 on 2022-06-28 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0012_remove_company_reg_no_alter_candidate_cv'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='vacancy',
            field=models.IntegerField(default=0),
        ),
    ]
